title: "The Animated Domain"
condensed_title: "Animated Domain"
author: "Srinivas Kaza"
description: "Do you want your possessions identified?"
#subheading: ""
more: "read more"
url: "http://kaza.io"
baseurl: ""

comments:
    isso: "comments.kaza.io"

style:
#    body: "whitesmoke"
    padding: 33%
    anchor: "#46f"
    special-heading: true
    nav: "#181818"
#    headline: "#06f"
    description: "white"
    article:
        odd: "#ffffff"
        even: "#222222"

links:
  - github-square: "https://github.com/AnimatedRNG"
  - stack-overflow: "http://stackoverflow.com/users/498680/animatedrng"

markdown: kramdown
paginate: 10
excerpt_separator: "\n\n\n"
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
gems: [jekyll-feed, jekyll-paginate, jekyll-sitemap]
